### ISSUE TITLE
load() got an unexpected keyword argument Loader

### ISSUE THREAD

**Issue by jaraco** [yougov/vr.launch#5]
Running the tests, I get this error:

```
______________________________________________________ [doctest] vr.launch.config.ConfigDict.from_yaml_stream _______________________________________________________
026 
027         >>> os.environ['PORT_TEST'] = '5000'
028         >>> ConfigDict.from_yaml_stream('port_test: ${PORT_TEST}')
UNEXPECTED EXCEPTION: TypeError("load() got an unexpected keyword argument 'Loader'")
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/doctest.py", line 1348, in __run
    exec(compile(example.source, filename, "single",
  File "<doctest vr.launch.config.ConfigDict.from_yaml_stream[1]>", line 1, in <module>
  File "/Users/jaraco/code/yougov/vr.launch/vr/launch/config.py", line 31, in from_yaml_stream
    return cls(yamlenv.load(stream, Loader=yaml.Loader))
TypeError: load() got an unexpected keyword argument 'Loader'
/Users/jaraco/code/yougov/vr.launch/vr/launch/config.py:28: UnexpectedException
```

**Comment by jaraco** [comment]
Best I can tell, that call [_never_ accepted that parameter](https://github.com/lbolla/yamlenv/commit/810530eb974b5e96dc2b3496a90f3e3e9be5a55c#diff-c810b28cdf78b3832aa573cb5c231882a8231835f0c3a83cd000505190d2b2a3R80). Looks like that bug was introduced in 99273afd036b02c859995e4071785f39e2171edd.

**Comment by jaraco** [comment]
After I fix that error, I get another error:

```
______________________________________________________ [doctest] vr.launch.config.ConfigDict.from_yaml_stream _______________________________________________________
026 
027         >>> os.environ['PORT_TEST'] = '5000'
028         >>> ConfigDict.from_yaml_stream('port_test: ${PORT_TEST}')
Expected:
    {'port_test': '5000'}
Got:
    {'port_test': 5000}

/Users/jaraco/code/yougov/vr.launch/vr/launch/config.py:28: DocTestFailure
```

**Comment by beizhengren** [comment]
how did you solve it?

**Comment by m-aciek** [comment]
by switching to integer with the expectation and starting to rely on `yamlenv>=0.6` https://github.com/yougov/vr.launch/commit/a8d06f7cba189d5cf6a9e63f621ef668e99e9358
